### ISSUE TITLE
What is `empty` for a SelectionSet

### ISSUE THREAD

**Issue by toastal** [purescript-graphql-client/purescript-graphql-client#25]
https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-SelectionSet#empty

Similar to this, how do I request an empty selections?

**Comment by srghma** [comment]
there is no such functionality, didnt think about it

it should gen
![2020-12-08-16:46:05-screenshot](https://user-images.githubusercontent.com/7573215/101498599-f4253200-3974-11eb-8828-ff6e59a80eca.png)

because empty is error

![2020-12-08-16:46:14-screenshot](https://user-images.githubusercontent.com/7573215/101498606-f5eef580-3974-11eb-93a9-3c0415494c84.png)

![2020-12-08-16:47:23-screenshot](https://user-images.githubusercontent.com/7573215/101498685-1028d380-3975-11eb-82ab-95fd9604cc79.png)

**Comment by srghma** [comment]
@toastal https://github.com/purescript-graphql-client/purescript-graphql-client/commit/656ae2cc9ad5769e0ddffcf52ae318e47960795c

probably should work

**Comment by toastal** [comment]
Neat. Yeah, I have a couple of use cases where I want to ignore the output.

**Comment by srghma** [comment]
ok, I think this is fixed, please reopen if I'm wrong
